const HAIFA_PORT = [32.82, 35.0];
const GOOGLE_MAPS_API_KEY = 'AIzaSyDulrR4TYXf5MncVDZgzZmNB_2ZlEsVrVY';
const PLAYBACK_SERVICE_URL = 'http://46951c3c.ngrok.io';
const PLAYBACK_SERVICE_URL_TEST = 'https://httpbin.org/get';

export { PLAYBACK_SERVICE_URL_TEST, PLAYBACK_SERVICE_URL, GOOGLE_MAPS_API_KEY, HAIFA_PORT };